import UIKit
import Capacitor
import FirebaseCore
import FirebaseMessaging
import UserNotifications

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        PushNotificationSetup.shared.configure()
        return true
    }


    // MARK: - Push Notifications Bridge
    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        PushNotificationSetup.shared.application(application, didRegisterForRemoteNotificationsWithDeviceToken: deviceToken)
    }

    func application(_ application: UIApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        PushNotificationSetup.shared.application(application, didFailToRegisterForRemoteNotificationsWithError: error)
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and invalidate graphics rendering callbacks. Games should use this method to pause the game.
    }

    func applicationDidEnterBackground(_ application: UIApplication) {
        // Use this method to release shared resources, save user data, invalidate timers, and store enough application state information to restore your application to its current state in case it is terminated later.
        // If your application supports background execution, this method is called instead of applicationWillTerminate: when the user quits.
    }

    func applicationWillEnterForeground(_ application: UIApplication) {
        // Called as part of the transition from the background to the active state; here you can undo many of the changes made on entering the background.
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
        // Restart any tasks that were paused (or not yet started) while the application was inactive. If the application was previously in the background, optionally refresh the user interface.
    }

    func applicationWillTerminate(_ application: UIApplication) {
        // Called when the application is about to terminate. Save data if appropriate. See also applicationDidEnterBackground:.
    }

    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey: Any] = [:]) -> Bool {
        // Called when the app was launched with a url. Feel free to add additional processing here,
        // but if you want the App API to support tracking app url opens, make sure to keep this call
        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
    }

    func application(_ application: UIApplication, continue userActivity: NSUserActivity, restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void) -> Bool {
        // Called when the app was launched with an activity, including Universal Links.
        // Feel free to add additional processing here, but if you want the App API to support
        // tracking app url opens, make sure to keep this call
        return ApplicationDelegateProxy.shared.application(application, continue: userActivity, restorationHandler: restorationHandler)
    }

}

// MARK: - Push Notification Setup (generated by scripts/rebuild-ios.sh)

final class PushNotificationSetup: NSObject, MessagingDelegate, UNUserNotificationCenterDelegate {

    static let shared = PushNotificationSetup()

    // ── Supabase config (same values already shipped in the web bundle) ──
    private let supabaseUrl = "https://cqzprtgcptqusmospdys.supabase.co"
    private let supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxenBydGdjcHRxdXNtb3NwZHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4MDA1NzUsImV4cCI6MjA5MDM3NjU3NX0.RvFLuvD-T9afp8r_EZ1vp0_2HvIPSFoJ5CRhwtHC5vk"

    // Key used by @capacitor/preferences to read from JS
    private let prefsKey = "CapacitorStorage.fcm_push_token"

    private override init() { super.init() }

    // Called from AppDelegate
    func configure() {
        if FirebaseApp.app() == nil {
            FirebaseApp.configure()
        }
        Messaging.messaging().delegate = self
        UNUserNotificationCenter.current().delegate = self

        print("[PushSetup] Firebase configured & delegates set")
    }

    // MARK: - MessagingDelegate

    func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
        guard let token = fcmToken, !token.isEmpty else { return }
        print("[PushSetup] FCM token: \(token.prefix(20))...")

        // 1. Persist to UserDefaults so JS can read via @capacitor/preferences
        UserDefaults.standard.set(token, forKey: prefsKey)

        // 2. Upsert to Supabase directly (guest row, user_id = null)
        upsertTokenToSupabase(token: token)
    }

    // MARK: - Foreground notification display

    func userNotificationCenter(
        _ center: UNUserNotificationCenter,
        willPresent notification: UNNotification,
        withCompletionHandler handler: @escaping (UNNotificationPresentationOptions) -> Void
    ) {
        // Show banner even when app is in foreground
        handler([.banner, .sound, .badge])
    }

    // MARK: - APNs → Capacitor bridge (keeps plugin working as fallback)

    func application(_ application: UIApplication,
                     didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
        NotificationCenter.default.post(
            name: .capacitorDidRegisterForRemoteNotifications,
            object: deviceToken
        )
    }

    func application(_ application: UIApplication,
                     didFailToRegisterForRemoteNotificationsWithError error: Error) {
        NotificationCenter.default.post(
            name: .capacitorDidFailToRegisterForRemoteNotifications,
            object: error
        )
    }

    // MARK: - Supabase REST upsert

    private func upsertTokenToSupabase(token: String) {
        guard let url = URL(string: "\(supabaseUrl)/rest/v1/push_device_tokens") else { return }

        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue("return=minimal", forHTTPHeaderField: "Prefer")
        // Upsert on token conflict
        request.setValue("token", forHTTPHeaderField: "on-conflict")
        request.setValue("resolution=merge-duplicates", forHTTPHeaderField: "Prefer")
        // Supabase requires both apikey header and Authorization
        request.setValue(supabaseAnonKey, forHTTPHeaderField: "apikey")
        request.setValue("Bearer \(supabaseAnonKey)", forHTTPHeaderField: "Authorization")

        let body: [String: Any] = [
            "token": token,
            "platform": "ios",
            "updated_at": ISO8601DateFormatter().string(from: Date())
        ]

        request.httpBody = try? JSONSerialization.data(withJSONObject: body)

        // Prefer header can only appear once — combine directives
        request.setValue("return=minimal,resolution=merge-duplicates", forHTTPHeaderField: "Prefer")

        URLSession.shared.dataTask(with: request) { _, response, error in
            if let error = error {
                print("[PushSetup] Supabase upsert error: \(error.localizedDescription)")
                return
            }
            if let http = response as? HTTPURLResponse {
                if (200...299).contains(http.statusCode) {
                    print("[PushSetup] Token saved to Supabase ✅")
                } else {
                    print("[PushSetup] Supabase upsert HTTP \(http.statusCode)")
                }
            }
        }.resume()
    }
}
